import 'dart:typed_data';
import 'package:flutter/services.dart' show rootBundle;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../models/sale.dart';
import '../models/user.dart';

/// Generates and prints/saves A4 sale invoices.
///
/// Supports English + Urdu labels. The bundled Arabic-script font
/// (Noto Naskh Arabic) is used so Urdu text renders in the PDF.
class InvoicePdf {
  static ByteData? _fontBytes;

  static const Map<String, String> _en = {
    'invoice': 'INVOICE',
    'bill': 'BILL',
    'date': 'Date',
    'time': 'Time',
    'invoiceNo': 'Invoice No',
    'billTo': 'Bill To',
    'customerId': 'Customer ID',
    'items': 'ITEMS',
    'item': 'Description',
    'qty': 'Qty',
    'karat': 'Krt',
    'weight': 'Wt (g)',
    'rate': 'Rate',
    'making': 'Making',
    'stone': 'Stone',
    'amount': 'Amount',
    'subtotal': 'Subtotal',
    'discount': 'Discount',
    'tax': 'Tax',
    'total': 'Total',
    'paid': 'Paid',
    'remaining': 'Remaining',
    'payment': 'Payment Method',
    'notes': 'Notes',
    'thanks': 'Thank you for your business!',
    'generated': 'Generated by Jewellery Shop Manager',
    'noItems': 'No items',
  };

  static const Map<String, String> _ur = {
    'invoice': 'رسید',
    'bill': 'بل',
    'date': 'تاریخ',
    'time': 'وقت',
    'invoiceNo': 'رسید نمبر',
    'billTo': 'بل از',
    'customerId': 'گاہک آئی ڈی',
    'items': 'اشیاء',
    'item': 'تفصیل',
    'qty': 'تعداد',
    'karat': 'قیراط',
    'weight': 'وزن (گرام)',
    'rate': 'ریٹ',
    'making': 'زر کاری',
    'stone': 'جواہرات',
    'amount': 'رقم',
    'subtotal': 'کل (بغیر کٹوتی)',
    'discount': 'رعایت',
    'tax': 'ٹیکس',
    'total': 'کل رقم',
    'paid': 'ادا شدہ',
    'remaining': 'باقی',
    'payment': 'ادائیگی کا طریقہ',
    'notes': 'نوٹس',
    'thanks': 'آپ کے کاروبار کے لیے شکریہ!',
    'generated': 'جیولری شاپ مینیجر کے ذریعے تیار شدہ',
    'noItems': 'کوئی اشیاء نہیں',
  };

  static Future<pw.Font> _loadBaseFont(ByteData? injected) async {
    if (injected != null) return pw.Font.ttf(injected);
    if (_fontBytes == null) {
      _fontBytes = await rootBundle.load('assets/fonts/NotoNaskhArabic.ttf');
    }
    return pw.Font.ttf(_fontBytes!);
  }

  static String _money(double v, ShopSettings s) {
    final digits = v.toStringAsFixed(0);
    final buf = StringBuffer();
    var n = digits;
    if (n.startsWith('-')) {
      buf.write('-');
      n = n.substring(1);
    }
    final len = n.length;
    for (var i = 0; i < len; i++) {
      buf.write(n[i]);
      final rem = len - i - 1;
      if (rem > 0 && rem % 3 == 0) buf.write(',');
    }
    return '${s.currency} ${buf.toString()}';
  }

  static String _w(double v) => v.toStringAsFixed(3);

  static Future<Uint8List> bytes(Sale sale, ShopSettings settings,
      {ByteData? fontData}) async {
    final isUr = settings.invoiceLanguage == 'ur';
    final d = isUr ? _ur : _en;
    final base = await _loadBaseFont(fontData);
    final theme = pw.ThemeData.withFont(
      base: base,
      bold: base, // fallback variant
    );
    final doc = pw.Document(theme: theme);

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(28),
        footer: (context) => pw.Container(
          alignment: pw.Alignment.center,
          child: pw.Text(
            '${d['generated']}  •  ${_ur['generated']}',
            style: pw.TextStyle(fontSize: 7, color: PdfColors.grey600),
          ),
        ),
        build: (context) => [
          // Shop header
          pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Expanded(
                flex: 3,
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      settings.shopName.isEmpty ? 'JEWELLERY SHOP' : settings.shopName,
                      style: pw.TextStyle(
                          fontSize: 20, fontWeight: pw.FontWeight.bold),
                    ),
                    if (settings.address.isNotEmpty)
                      pw.Text(settings.address,
                          style: const pw.TextStyle(fontSize: 9)),
                    if (settings.phone.isNotEmpty)
                      pw.Text(settings.phone,
                          style: const pw.TextStyle(fontSize: 9)),
                  ],
                ),
              ),
              pw.Expanded(
                flex: 2,
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.end,
                  children: [
                    pw.Text(d['invoice']!,
                        style: pw.TextStyle(
                            fontSize: 16, fontWeight: pw.FontWeight.bold)),
                    pw.SizedBox(height: 2),
                    pw.Text('${d['invoiceNo']}: ${sale.invoiceId}',
                        style: const pw.TextStyle(fontSize: 9)),
                    pw.Text(
                        '${d['date']}: ${_fmtDate(sale.saleDate)}  ${d['time']}: ${_fmtTime(sale.saleDate)}',
                        style: const pw.TextStyle(fontSize: 9)),
                  ],
                ),
              ),
            ],
          ),
          pw.Divider(color: PdfColors.black),
          pw.SizedBox(height: 6),
          // Bill to
          pw.Row(children: [
            pw.Text('${d['billTo']}: ',
                style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold)),
            pw.Text(sale.customerName, style: const pw.TextStyle(fontSize: 10)),
            pw.SizedBox(width: 16),
            if (sale.customerId > 0)
              pw.Text('${d['customerId']}: ${sale.customerId}',
                  style: const pw.TextStyle(fontSize: 10)),
          ]),
          pw.SizedBox(height: 10),
          // Items table
          pw.TableHelper.fromTextArray(
            headers: [
              d['item']!,
              d['qty']!,
              d['karat']!,
              d['weight']!,
              d['rate']!,
              d['making']!,
              d['stone']!,
              d['amount']!,
            ],
            data: sale.items.isEmpty
                ? [
                    ['-', '-', '-', '-', '-', '-', '-', d['noItems']!]
                  ]
                : [
                    for (final it in sale.items)
                      [
                        it.productName,
                        '${it.quantity}',
                        '${it.karat}K',
                        _w(it.netWeight),
                        _money(it.goldRate, settings),
                        '${it.makingCharges.toStringAsFixed(0)}',
                        '${it.stoneCharges.toStringAsFixed(0)}',
                        _money(it.lineTotal, settings),
                      ]
                  ],
            border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.5),
            headerDecoration: const pw.BoxDecoration(
                color: PdfColors.grey100, borderRadius: const pw.BorderRadius.all(pw.Radius.circular(2))),
            headerStyle:
                pw.TextStyle(fontSize: 8, fontWeight: pw.FontWeight.bold),
            cellStyle: const pw.TextStyle(fontSize: 8),
            headerAlignment: pw.Alignment.center,
            cellAlignment: pw.Alignment.centerLeft,
          ),
          pw.SizedBox(height: 12),
          // Totals
          pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Expanded(flex: 3, child: pw.SizedBox.shrink()),
              pw.Expanded(
                flex: 2,
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.stretch,
                  children: [
                    _totalRow(d['subtotal']!, _money(sale.subtotal, settings)),
                    _totalRow(d['discount']!, '- ${_money(sale.totalDiscount, settings)}'),
                    _totalRow(d['tax']!, _money(sale.tax, settings)),
                    pw.Divider(color: PdfColors.black),
                    _totalRow(d['total']!, _money(sale.total, settings),
                        bold: true),
                    _totalRow(d['paid']!, _money(sale.paid, settings)),
                    _totalRow(d['remaining']!,
                        _money(sale.remaining, settings)),
                    pw.SizedBox(height: 6),
                    pw.Text(
                        '${d['payment']}: ${sale.paymentMethod}',
                        style: const pw.TextStyle(fontSize: 9)),
                  ],
                ),
              ),
            ],
          ),
          pw.SizedBox(height: 12),
          pw.Divider(color: PdfColors.grey300),
          if (sale.notes.isNotEmpty)
            pw.Padding(
              padding: const pw.EdgeInsets.only(top: 6),
              child: pw.Text('${d['notes']}: ${sale.notes}',
                  style: const pw.TextStyle(fontSize: 9)),
            ),
          pw.SizedBox(height: 16),
          pw.Text(d['thanks']!,
              style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold)),
        ],
      ),
    );
    return doc.save();
  }

  static pw.Widget _totalRow(String label, String value, {bool bold = false}) {
    final style = pw.TextStyle(
        fontSize: bold ? 11 : 9, fontWeight: pw.FontWeight.bold);
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 1.5),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label, style: style),
          pw.Text(value, style: style),
        ],
      ),
    );
  }

  static String _fmtDate(DateTime? dt) {
    if (dt == null) return '-';
    final m = '${dt.month}'.padLeft(2, '0');
    final dd = '${dt.day}'.padLeft(2, '0');
    return '$dd/$m/${dt.year}';
  }

  static String _fmtTime(DateTime? dt) {
    if (dt == null) return '-';
    final h = '${dt.hour}'.padLeft(2, '0');
    final mi = '${dt.minute}'.padLeft(2, '0');
    return '$h:$mi';
  }

  /// Opens the OS print dialog (also allows saving via the printer dialog).
  static Future<bool> printInvoice(Sale sale, ShopSettings settings) {
    return Printing.layoutPdf(
      name: 'invoice_${sale.invoiceId}',
      onLayout: (format) async => await bytes(sale, settings),
    );
  }
}