import 'dart:typed_data';
import 'package:flutter/services.dart' show rootBundle;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

/// Generates A4 PDF reports (generic title + column table + totals).
///
/// Reuses the same font handling as invoices so Urdu/English text renders.
class ReportPdf {
  static ByteData? _fontBytes;

  static Future<pw.Font> _loadBaseFont(ByteData? injected) async {
    if (injected != null) return pw.Font.ttf(injected);
    _fontBytes ??=
        await rootBundle.load('assets/fonts/NotoNaskhArabic.ttf');
    return pw.Font.ttf(_fontBytes!);
  }

  /// Builds a report document with a title banner, table, and totals block.
  static Future<Uint8List> bytes({
    required String title,
    required String subtitle,
    required List<String> columns,
    required List<List<String>> rows,
    required String shopName,
    required String currency,
    Map<String, String>? totals,
    ByteData? fontData,
  }) async {
    final base = await _loadBaseFont(fontData);
    final theme = pw.ThemeData.withFont(base: base, bold: base);
    final doc = pw.Document(theme: theme);

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(28),
        footer: (context) => pw.Container(
          alignment: pw.Alignment.center,
          child: pw.Text(
            'Generated by Jewellery Shop Manager  •  بتاريخ گزارش',
            style: pw.TextStyle(fontSize: 7, color: PdfColors.grey600),
          ),
        ),
        build: (ctx) => [
          pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Expanded(
                flex: 3,
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      shopName.isEmpty ? 'JEWELLERY SHOP' : shopName,
                      style: pw.TextStyle(
                          fontSize: 18, fontWeight: pw.FontWeight.bold),
                    ),
                    pw.SizedBox(height: 2),
                    pw.Text(title,
                        style: pw.TextStyle(
                            fontSize: 13, color: PdfColors.grey800)),
                    pw.Text(subtitle,
                        style:
                            pw.TextStyle(fontSize: 9, color: PdfColors.grey600)),
                  ],
                ),
              ),
              pw.Expanded(
                flex: 2,
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.end,
                  children: [
                    pw.Text('Report  •  رپورٹ',
                        style: pw.TextStyle(
                            fontSize: 16, fontWeight: pw.FontWeight.bold)),
                    pw.Text('Generated: ${_now()}',
                        style: const pw.TextStyle(fontSize: 9)),
                  ],
                ),
              ),
            ],
          ),
          pw.Divider(color: PdfColors.black),
          pw.SizedBox(height: 8),
          if (rows.isEmpty)
            pw.Padding(
              padding: const pw.EdgeInsets.symmetric(vertical: 24),
              child: pw.Text('No records',
                  style: const pw.TextStyle(color: PdfColors.grey500)),
            )
          else ...[
            pw.TableHelper.fromTextArray(
              headers: columns,
              data: rows,
              border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.5),
              headerDecoration: const pw.BoxDecoration(
                  color: PdfColors.grey100,
                  borderRadius: pw.BorderRadius.all(pw.Radius.circular(2))),
              headerStyle:
                  pw.TextStyle(fontSize: 8, fontWeight: pw.FontWeight.bold),
              cellStyle: const pw.TextStyle(fontSize: 8),
              headerAlignment: pw.Alignment.centerLeft,
              cellAlignment: pw.Alignment.centerLeft,
            ),
            if (totals != null && totals.isNotEmpty) ...[
              pw.SizedBox(height: 12),
              pw.Divider(color: PdfColors.grey400),
              pw.SizedBox(height: 6),
              for (final e in totals.entries)
                pw.Padding(
                  padding: const pw.EdgeInsets.symmetric(vertical: 1.5),
                  child: pw.Row(
                    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                    children: [
                      pw.Text(e.key,
                          style: pw.TextStyle(
                              fontSize: 10, fontWeight: pw.FontWeight.bold)),
                      pw.Text(e.value,
                          style: pw.TextStyle(
                              fontSize: 10, fontWeight: pw.FontWeight.bold)),
                    ],
                  ),
                ),
            ],
          ],
          pw.SizedBox(height: 16),
          pw.Divider(color: PdfColors.grey300),
        ],
      ),
    );
    return doc.save();
  }

  static String _now() {
    final t = DateTime.now();
    final d = '${t.day}'.padLeft(2, '0');
    final m = '${t.month}'.padLeft(2, '0');
    final h = '${t.hour}'.padLeft(2, '0');
    final mi = '${t.minute}'.padLeft(2, '0');
    return '$d/$m/${t.year} $h:$mi';
  }
}