<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <style>
        * { box-sizing: border-box; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1c1917; margin: 0; }
        .head { border-bottom: 3px solid #0f766e; padding-bottom: 10px; margin-bottom: 14px; }
        .head h1 { margin: 0 0 4px; font-size: 20px; color: #0f766e; }
        .meta { color: #57534e; font-size: 10px; }
        .meta span { display: inline-block; margin-right: 18px; }
        table { width: 100%; border-collapse: collapse; }
        th { background: #f5f5f4; text-align: left; padding: 5px 6px; font-size: 10px; text-transform: uppercase; letter-spacing: .02em; border-bottom: 1px solid #d6d3d1; }
        td { padding: 4px 6px; border-bottom: 1px solid #e7e5e4; }
        tr:nth-child(even) td { background: #fafaf9; }
        .num { text-align: right; }
        .totals { margin-top: 14px; border-top: 2px solid #d6d3d1; padding-top: 8px; }
        .totals div { display: flex; justify-content: space-between; max-width: 420px; font-weight: bold; }
        .foot { margin-top: 20px; font-size: 9px; color: #78716c; border-top: 1px solid #d6d3d1; padding-top: 6px; }
    </style>
</head>
<body>
    <div class="head">
        <h1>{{ $shopName }}</h1>
        <div class="meta">
            <span>{{ $title }}</span>
            <span>{{ $from }} to {{ $to }}</span>
            <span>Generated: {{ now()->format('Y-m-d H:i') }}</span>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                @foreach ($headings as $h) <th>{{ $h }}</th> @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse ($rows as $row)
                <tr>
                    @foreach ($row as $i => $cell)
                        <td class="{{ $i === 0 ? '' : 'num' }}">{{ $cell }}</td>
                    @endforeach
                </tr>
            @empty
                <tr><td colspan="{{ count($headings) }}" style="text-align:center;color:#a8a29e;">No records in this period.</td></tr>
            @endforelse
        </tbody>
    </table>

    @if ($totals)
        <div class="totals">
            @foreach ($totals as $label => $value)
                <div><span>{{ $label }}</span><span>{{ $value }}</span></div>
            @endforeach
        </div>
    @endif

    <div class="foot">Generated by Jewellery Shop Manager &middot; Confidential business report</div>
</body>
</html>